Update compile
added option to skip maven build when a war file is directly provided

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -52,22 +52,24 @@ curl --silent --max-time 10 --location $MAVEN_SETTINGS_URL --output .m2/settings
 echo " done"
 
 # change to build dir to run maven
-cd $BUILD_DIR
+if [ -f $BUILD_DIR/pom.xml ]; then
+  cd $BUILD_DIR
 
-export MAVEN_OPTS="-Xmx512m"
+  export MAVEN_OPTS="-Xmx512m"
 
-# build app
-BUILDCMD="$CACHE_DIR/.maven/bin/mvn -B -Duser.home=$BUILD_DIR -Dmaven.repo.local=$CACHE_DIR/.m2/repository -s $CACHE_DIR/.m2/settings.xml -DskipTests=true clean install"
-echo "-----> executing $BUILDCMD"
+  # build app
+  BUILDCMD="$CACHE_DIR/.maven/bin/mvn -B -Duser.home=$BUILD_DIR -Dmaven.repo.local=$CACHE_DIR/.m2/repository -s $CACHE_DIR/.m2/settings.xml -DskipTests=true clean install
+  
+  echo "-----> executing $BUILDCMD"
 
-if [ -f pom.xml ]; then
   $BUILDCMD 2>&1 | sed -u 's/^/       /'
+
+  if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+    echo " !     Failed to build app with Maven"
+    exit 1
+  fi
 fi
 
-if [ "${PIPESTATUS[*]}" != "0 0" ]; then
-  echo " !     Failed to build app with Maven"
-  exit 1
-fi
 
 # include .files when moving things around
 shopt -s dotglob
@@ -86,7 +88,12 @@ sed -i "s/8080/\$PORT/g" ~/apache-tomee-plus-$TOMEE_VERSION/conf/server.xml
 sed -i "s/8005/-1/g"     ~/apache-tomee-plus-$TOMEE_VERSION/conf/server.xml
 sed -i "s/.*8009.*//g"   ~/apache-tomee-plus-$TOMEE_VERSION/conf/server.xml
 
-mv ~/target/*.war ~/apache-tomee-plus-$TOMEE_VERSION/webapps/ROOT.war
+if [ -f pom.xml ]; then
+  mv ~/target/*.war ~/apache-tomee-plus-$TOMEE_VERSION/webapps/ROOT.war
+else 
+  mv *.war ~/apache-tomee-plus-$TOMEE_VERSION/webapps/ROOT.war
+fi
+
 ~/apache-tomee-plus-$TOMEE_VERSION/bin/catalina.sh run
 EOF
 
